from .analysis import AnalysisTab
from .batch_run import BatchTab
from .body_draw import DrawBodyTab
from .env_draw import DrawEnvTab
from .env import EnvTab
from .essay import EssayTab
from .importing import ImportTab
from .intro import IntroTab
from .life_history import LifeTab
from .model import ModelTab
from .settings import SettingsTab
from .simulation import SimTab
from .tutorial import TutorialTab
from .videos import VideoTab