LarvaConfDic = {
    'physics.torque_coef': [1.78, (0.01, 10.0), 'torque coefficient'],
    'physics.ang_damping': [3.6, (0.0, 5.0), 'angular damping'],
    'physics.body_spring_k': [10, (0.0, 100.0), 'torsional spring constant'],
    'physics.bend_correction_coef': [1.0, (0.0, 2.0), 'bend correction coefficient'],
    'brain.crawler_params.initial_freq': [1.37, (1.0, 2.0), 'crawling frequency'],
    'brain.crawler_params.stride_dst_std': [0.033, (0.0, 0.5), 'std distance per stride'],
    # 'conf.crawler_params.stride_dst_mean': [0.23, (0.05, 0.6), 'mean distance per stride'],
    # 'conf.crawler_params.max_vel_phase': [3.6, (0.1, 6.2), 'stride phase of max velocity'],
    # 'conf.turner_params.base_activation': [14, (10.0, 40.0), 'turner base-activation'],
    # 'conf.interference_params.attenuation': [0.03, (0.0, 1.0), 'interference coefficient'],
    # 'conf.interference_params.attenuation_min': [0.23, (0.0, 1.0), 'baseline interference suppression'],
    # 'conf.interference_params.attenuation_max': [0.2, (0.0, 1.0), 'min interference suppression'],
}

ChemoConfDict = {**LarvaConfDic,
'brain.olfactor_params.odor_dict.Odor.mean': [0.0, (-500.0, 500.0), 'Odor gain'],
'brain.olfactor_params.decay_coef': [0.0, (0.0, 10.0), 'Olfactory decay coefficient'],
'brain.olfactor_params.input_noise': [0.0, (0.0, 10.0), 'Olfactory noise'],
'brain.olfactor_params.brute_force': [False, (None, None), 'Run interruption allowed'],
'brain.olfactor_params.perception': ['log', ['log', 'linear'], 'Sensory mode'],
'brain.interference_params.mode': ['square', ['square', 'phasic'], 'Interference mode'],
'brain.interference_params.suppression_mode': ['amplitude', ['amplitude', 'oscillation', 'both'], 'Interference suppression mode'],
'brain.interference_params.attenuation': [1.0, (0.0, 1.0), 'Interference attenuation coef'],
'brain.interference_params.attenuation_min': [0.0, (0.0, 1.0), 'Interference attenuation min'],
'brain.interference_params.attenuation_max': [0.0, (0.0, 1.0), 'Interference attenuation max'],
    # 'torque_coef': [1.78, (0.01, 10.0), 'torque coefficient'],
    # 'ang_damp_coef': [3.6, (0.0, 5.0), 'angular damping'],
    # 'body_spring_k': [10, (0.0, 100.0), 'torsional spring constant'],
    # 'bend_correction_coef': [1.0, (0.0, 2.0), 'bend correction coefficient'],
    # 'conf.crawler_params.initial_freq': [1.37, (1.0, 2.0), 'crawling frequency'],
    # 'conf.crawler_params.stride_dst_std': [0.033, (0.0, 0.5), 'std distance per stride'],
    # 'conf.crawler_params.stride_dst_mean': [0.23, (0.05, 0.6), 'mean distance per stride'],
    # 'conf.crawler_params.max_vel_phase': [3.6, (0.1, 6.2), 'stride phase of max velocity'],
    # 'conf.turner_params.base_activation': [14, (10.0, 40.0), 'turner base-activation'],
    # 'conf.interference_params.attenuation': [0.03, (0.0, 1.0), 'interference coefficient'],
    # 'conf.interference_params.attenuation_min': [0.23, (0.0, 1.0), 'baseline interference suppression'],
    # 'conf.interference_params.attenuation_max': [0.2, (0.0, 1.0), 'min interference suppression'],
}
