from .analysis import AnalysisTab
from .batch_run import BatchTab
from .draw_body_tab import DrawBodyTab
from .draw_env_tab import DrawEnvTab
from .env_tab import EnvTab
from .essay_tab import EssayTab
from .import_tab import ImportTab
from .intro import IntroTab
from .life_history import LifeTab
from .model_tab import ModelTab
from .settings import SettingsTab
from .sim_tab import SimTab
from .tutorial import TutorialTab
from .videos import VideoTab