"""Curated catalog of beginner-facing behavioral scenarios.

The registry ships 57 experiment configurations whose IDs (``PItest_off_OSN``,
``RvsS_on_q15``, ``noMB_patch_grid``) mean nothing to a newcomer, and whose
durations range from 30 seconds to 24 hours. This module hand-picks a small set,
gives each a human title and an explanation, and caps how long it runs, so the
Explore app can offer "pick one and watch" with no configuration.

The behavioral grouping mirrors the categories used in ``Exp_dict`` in
``larvaworld.lib.reg.stored_confs.sim_conf``. That grouping is flattened away
when configs are materialized into the registry, so it is re-declared here.
This is deliberately portal-side curation: it must not leak into core config.

Data only - no Panel imports, so this stays cheap and unit-testable.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Scenario:
    """One curated, ready-to-watch experiment.

    Attributes:
        id: Stable identifier used in URLs and tests.
        exp_id: A stored ``Exp`` configuration ID; must exist in the registry.
        category: Behavioral grouping used to section the gallery.
        title: Human-readable name shown on the card.
        teaser: One sentence describing what the viewer will see.
        explanation: Two to four sentences on what the behavior means.
        step_cap: Maximum simulation steps for the Explore run.
        n_agents: Number of larvae, kept small so individuals stay legible.
        literature: Optional source publication for the paradigm.
        watch_for: Short bullet hints on what to look at while it runs.
    """

    id: str
    exp_id: str
    category: str
    title: str
    teaser: str
    explanation: str
    step_cap: int = 600
    n_agents: int = 8
    literature: str | None = None
    watch_for: tuple[str, ...] = field(default_factory=tuple)


#: Display order and human names for the behavioral categories.
CATEGORY_TITLES: dict[str, str] = {
    "exploration": "Exploration",
    "chemotaxis": "Chemotaxis - following odors",
    "foraging": "Foraging - finding and eating food",
    "anemotaxis": "Anemotaxis - responding to wind",
    "growth": "Growth and phenotype",
    "games": "Games and interaction",
}

CATEGORY_ORDER: tuple[str, ...] = tuple(CATEGORY_TITLES)


SCENARIOS: tuple[Scenario, ...] = (
    Scenario(
        id="dish",
        exp_id="dish",
        category="exploration",
        title="Free exploration in a Petri dish",
        teaser="Larvae crawl freely on plain agar with nothing to chase.",
        explanation=(
            "With no food and no odor, behavior is driven entirely by the larva's "
            "own motor program. Crawling alternates with turning in bouts, which "
            "produces the characteristic run-and-turn path. This is the baseline "
            "every other experiment is compared against."
        ),
        step_cap=600,
        n_agents=10,
        watch_for=(
            "Runs of forward crawling interrupted by sharp turns",
            "No preferred direction - the population spreads evenly",
        ),
    ),
    Scenario(
        id="dispersion",
        exp_id="dispersion",
        category="exploration",
        title="Spreading out from the centre",
        teaser="Larvae all start clustered in the middle and disperse outward.",
        explanation=(
            "Starting every larva at the same point makes the spread over time "
            "measurable. How fast the cloud expands is a compact summary of how "
            "active and how directionally persistent the animals are."
        ),
        step_cap=600,
        n_agents=15,
        watch_for=(
            "The cluster loosening into a widening ring",
            "Individuals that wander much further than the rest",
        ),
    ),
    Scenario(
        id="focus",
        exp_id="focus",
        category="exploration",
        title="One larva up close",
        teaser="A single larva in a tiny arena, big enough to see the body bend.",
        explanation=(
            "Zooming in on one animal shows what the population view hides: the "
            "body is a chain of segments, and forward waves and lateral bends are "
            "generated by separate rhythmic circuits that interact."
        ),
        step_cap=400,
        n_agents=1,
        watch_for=(
            "The peristaltic wave travelling along the body",
            "Head sweeps preceding a change of direction",
        ),
    ),
    Scenario(
        id="chemotaxis",
        exp_id="chemotaxis",
        category="chemotaxis",
        title="Navigating up an odor gradient",
        teaser="Larvae start away from an odor source and steer towards it.",
        explanation=(
            "The larva samples odor concentration as it moves and turns more when "
            "conditions worsen. That simple rule, applied continuously, produces "
            "reliable navigation towards the source without any map or memory."
        ),
        step_cap=700,
        n_agents=10,
        literature="Gomez-Marin et al. (2012)",
        watch_for=(
            "Paths biased towards the odor source",
            "More head casting when heading the wrong way",
        ),
    ),
    Scenario(
        id="chemorbit",
        exp_id="chemorbit",
        category="chemotaxis",
        title="Local search around an odor source",
        teaser="Larvae placed near an odor stay close and circle it.",
        explanation=(
            "Once at the source, the strategy switches from approach to staying "
            "put. The result looks like orbiting: repeated small excursions that "
            "keep returning. This is exploitation rather than exploration."
        ),
        step_cap=700,
        n_agents=10,
        literature="Gomez-Marin et al. (2012)",
        watch_for=(
            "Tight loops near the centre rather than straight runs",
            "Excursions that turn back before getting far",
        ),
    ),
    Scenario(
        id="CS_UCS_off",
        exp_id="PItest_off",
        category="chemotaxis",
        title="Odor choice without food reward",
        teaser="Two odor cues remain in the arena after the food reward is removed.",
        explanation=(
            "This is the test-phase environment for odor preference experiments. "
            "The conditioned stimuli remain available, but there is no food reward, "
            "so the resulting paths isolate odor-driven choice from feeding behavior."
        ),
        step_cap=600,
        n_agents=10,
        watch_for=(
            "Choices between the two odor sources",
            "Search paths without feeding stops",
        ),
    ),
    Scenario(
        id="patchy_food",
        exp_id="patchy_food",
        category="foraging",
        title="Foraging between food patches",
        teaser="Discrete food patches are scattered in the arena.",
        explanation=(
            "Feeding and locomotion compete for control. On a patch the larva "
            "slows and feeds; off it, it searches. How long an animal stays before "
            "moving on is the classic patch-residence question in foraging theory."
        ),
        step_cap=800,
        n_agents=10,
        watch_for=(
            "Slowing down on contact with a patch",
            "Departures once a patch is depleted",
        ),
    ),
    Scenario(
        id="uniform_food",
        exp_id="uniform_food",
        category="foraging",
        title="Feeding on a uniform food lawn",
        teaser="The whole arena is covered in nutritious substrate.",
        explanation=(
            "With food everywhere there is nothing to search for, so exploration "
            "collapses and feeding dominates. Compare the paths here with the "
            "Petri dish scenario to see how strongly food suppresses movement."
        ),
        step_cap=700,
        n_agents=10,
        watch_for=(
            "Much shorter runs than on plain agar",
            "Long stationary feeding bouts",
        ),
    ),
    Scenario(
        id="anemotaxis",
        exp_id="anemotaxis",
        category="anemotaxis",
        title="Orienting in wind",
        teaser="A steady airflow crosses the arena and larvae respond to it.",
        explanation=(
            "Mechanosensory hairs report airflow direction, giving the larva a "
            "directional cue that does not depend on chemical gradients. Wind "
            "responses combine with odor tracking in natural plume following."
        ),
        step_cap=300,
        n_agents=10,
        watch_for=("Headings biased relative to the wind direction",),
    ),
    Scenario(
        id="RvsS",
        exp_id="RvsS",
        category="growth",
        title="Rovers versus sitters",
        teaser="Two foraging phenotypes are simulated side by side.",
        explanation=(
            "Rover and sitter are natural variants of the foraging gene. Rovers "
            "move more and leave food sooner; sitters stay and exploit. Both are "
            "viable strategies, which is why the variation persists in the wild."
        ),
        step_cap=700,
        n_agents=10,
        literature="Kaun et al. (2007)",
        watch_for=(
            "One group covering noticeably more ground",
            "Different residence times on food",
        ),
    ),
    Scenario(
        id="maze",
        exp_id="maze",
        category="games",
        title="Solving a maze",
        teaser="Walls block the direct route to an odor source.",
        explanation=(
            "Odor navigation meets physical obstacles. The larva has no plan and "
            "no memory of the layout, so it must combine gradient following with "
            "wall contact - which sometimes works and sometimes leads to dead ends."
        ),
        step_cap=800,
        n_agents=6,
        watch_for=(
            "Following walls when the gradient is blocked",
            "Backtracking out of dead ends",
        ),
    ),
)


def scenario_by_id(scenario_id: str) -> Scenario | None:
    """Return the scenario with this ID, or ``None``."""
    for scenario in SCENARIOS:
        if scenario.id == scenario_id:
            return scenario
    return None


def scenarios_by_category() -> dict[str, list[Scenario]]:
    """Group the catalog by category, in :data:`CATEGORY_ORDER`."""
    grouped: dict[str, list[Scenario]] = {}
    for category in CATEGORY_ORDER:
        matching = [s for s in SCENARIOS if s.category == category]
        if matching:
            grouped[category] = matching
    return grouped


def validate_scenarios(*, known_exp_ids: set[str] | None = None) -> None:
    """Check catalog invariants.

    Args:
        known_exp_ids: Experiment IDs available in the registry. When omitted,
            registry membership is not checked (keeps unit tests import-light).

    Raises:
        ValueError: If any invariant is violated.
    """

    def _err(msg: str) -> None:
        raise ValueError(f"[larvaworld.portal.explore] {msg}")

    ids = [s.id for s in SCENARIOS]
    if len(ids) != len(set(ids)):
        _err("Duplicate scenario ids")

    for scenario in SCENARIOS:
        if scenario.category not in CATEGORY_TITLES:
            _err(
                f"Scenario '{scenario.id}' has unknown category "
                f"'{scenario.category}'"
            )
        if not scenario.title.strip() or not scenario.teaser.strip():
            _err(f"Scenario '{scenario.id}' is missing title or teaser")
        if not scenario.explanation.strip():
            _err(f"Scenario '{scenario.id}' is missing an explanation")
        if scenario.step_cap <= 0 or scenario.step_cap > 2000:
            _err(
                f"Scenario '{scenario.id}' step_cap={scenario.step_cap} is outside "
                "the bounded range (1..2000)"
            )
        if scenario.n_agents <= 0 or scenario.n_agents > 50:
            _err(
                f"Scenario '{scenario.id}' n_agents={scenario.n_agents} is outside "
                "the legible range (1..50)"
            )
        if known_exp_ids is not None and scenario.exp_id not in known_exp_ids:
            _err(
                f"Scenario '{scenario.id}' references unknown experiment "
                f"'{scenario.exp_id}'"
            )
